f = open('src/pages/admin/RoundTest.tsx', encoding='utf-8')
c = f.read()
f.close()
bt = chr(96)
print('errors found:')
print('glass-card p-6 max-w-md' in c)
print('ext-3xl font-display mb-2' in c)
print('ext-sm px-3' in c)
print('ext-xs px-2' in c)
