f = open('src/pages/admin/ScenarioEdit.tsx', encoding='utf-8')
c = f.read()
f.close()
c = c.replace('назадад???????', 'назад')
c = c.replace('Порог победы команды????????', 'Порог победы саботажника')
f = open('src/pages/admin/ScenarioEdit.tsx', 'w', encoding='utf-8', newline='\n')
f.write(c)
f.close()
print('done')
