import re
p='src/pages/admin/ScenarioEdit.tsx'
c=open(p,encoding='utf-8').read()
c=c.replace('  const [partyGame, setPartyGame] = useState<PartyGame | null>(null);','  const [partyGame, setPartyGame] = useState<PartyGame | null>(null);\n  const [characters, setCharacters] = useState<any[]>([]);')
c=c.replace('      if (data.scenario_json?.party_game) setPartyGame(data.scenario_json.party_game as PartyGame);','      if (data.scenario_json?.party_game) setPartyGame(data.scenario_json.party_game as PartyGame);\n      setCharacters(data.scenario_json?.characters ?? []);')
c=c.replace('    const newJson = { ...scenarioJson, ...(partyGame ? { party_game: partyGame } : {}) };','    const newJson = { ...scenarioJson, ...(partyGame ? { party_game: partyGame } : {}), characters };')
c=c.replace('  const [tab, setTab] = useState<"basic"|"intro"|"rounds"|"endings">("basic");','  const [tab, setTab] = useState<"basic"|"intro"|"roles"|"rounds"|"endings">("basic");')
c=c.replace('{tab === "rounds" && partyGame && (','{tab === "roles" && (\n          <div className="grid gap-4">\n            <div className="flex items-center justify-between">\n              <p className="text-xs uppercase tracking-widest text-muted-foreground">Персонажи (до 8)</p>\n              {characters.length < 8 && (\n                <button onClick={() => setCharacters([...characters, { id: "char-" + Date.now(), name: "", description: "", traits: [] }])}\n                  className="flex items-center gap-1 text-xs text-portal border border-portal/30 px-2 py-1 rounded hover:bg-portal/10">\n                  <Plus className="w-3 h-3" /> Добавить\n                </button>\n              )}\n            </div>\n            {characters.map((char, ci) => (\n              <div key={char.id} className="glass-card p-5 grid gap-3">\n                <div className="flex items-center justify-between">\n                  <span className="text-xs font-mono text-portal">#{ci + 1}</span>\n                  <button onClick={() => setCharacters(characters.filter((_, i) => i !== ci))}\n                    className="text-destructive hover:text-destructive/80"><Trash2 className="w-4 h-4" /></button>\n                </div>\n                <TextField label="Имя" value={char.name} onChange={(v) => { const arr = [...characters]; arr[ci] = { ...arr[ci], name: v }; setCharacters(arr); }} />\n                <TextField label="Описание" value={char.description} onChange={(v) => { const arr = [...characters]; arr[ci] = { ...arr[ci], description: v }; setCharacters(arr); }} />\n                <div className="grid gap-1">\n                  <label className="text-xs uppercase tracking-widest text-muted-foreground">Черты (через запятую)</label>\n                  <input type="text" value={(char.traits ?? []).join(", ")}\n                    onChange={(e) => { const arr = [...characters]; arr[ci] = { ...arr[ci], traits: e.target.value.split(",").map((t) => t.trim()).filter(Boolean) }; setCharacters(arr); }}\n                    className="w-full bg-muted border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-portal" />\n                </div>\n              </div>\n            ))}\n          </div>\n        )}\n        {tab === "rounds" && partyGame && (')
open(p,'w',encoding='utf-8',newline='\n').write(c)
print('SE ok')
