f = open('src/pages/admin/ScenarioEdit.tsx', encoding='utf-8')
c = f.read()
f.close()
c = c.replace('"fail_host","fail_morty"],', '"fail_host","fail_morty","tie_host","tie_morty"],', 1)
c = c.replace('  fail_host: "Рик (провал)", fail_morty: "Морти (провал)",', '  fail_host: "Рик (провал)", fail_morty: "Морти (провал)",\n  tie_host: "Рик (ничья)", tie_morty: "Морти (ничья)",')
f = open('src/pages/admin/ScenarioEdit.tsx', 'w', encoding='utf-8')
f.write(c)
f.close()
print('done')
