f = open('src/components/MediaUpload.tsx', 'w', encoding='utf-8', newline='\n')
f.write('import { useState, useRef } from "react";\n')
f.write('import { supabase } from "@/integrations/supabase/client";\n')
f.write('import { Loader2, Upload, X, Music, Image } from "lucide-react";\n')
f.write('\n')
f.write('interface MediaUploadProps {\n')
f.write('  scenarioId: string;\n')
f.write('  path: string;\n')
f.write('  type: "audio" | "image";\n')
f.write('  currentUrl?: string;\n')
f.write('  onUploaded: (path: string) => void;\n')
f.write('  onRemoved: () => void;\n')
f.write('}\n')
f.write('\n')
f.write('export function MediaUpload({ scenarioId, path, type, currentUrl, onUploaded, onRemoved }: MediaUploadProps) {\n')
f.write('  const [uploading, setUploading] = useState(false);\n')
f.write('  const [error, setError] = useState<string | null>(null);\n')
f.write('  const inputRef = useRef<HTMLInputElement>(null);\n')
f.write('  const ext = type === "audio" ? "mp3" : "jpg";\n')
f.write('  const storagePath = `${scenarioId}/${path}.${ext}`;\n')
f.write('  const baseUrl = import.meta.env.VITE_SUPABASE_URL;\n')
f.write('  const publicUrl = `${baseUrl}/storage/v1/object/public/scenario-media/${storagePath}`;\n')
f.write('  const accept = type === "audio" ? "audio/mp3,audio/mpeg,audio/wav" : "image/jpeg,image/png,image/webp";\n')
f.write('  const Icon = type === "audio" ? Music : Image;\n')
f.write('\n')
f.write('  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {\n')
f.write('    const file = e.target.files?.[0];\n')
f.write('    if (!file) return;\n')
f.write('    setUploading(true); setError(null);\n')
f.write('    try {\n')
f.write('      const { error: uploadError } = await supabase.storage\n')
f.write('        .from("scenario-media")\n')
f.write('        .upload(storagePath, file, { upsert: true });\n')
f.write('      if (uploadError) throw uploadError;\n')
f.write('      onUploaded(storagePath);\n')
f.write('    } catch (err: any) {\n')
f.write('      setError(err.message);\n')
f.write('    } finally {\n')
f.write('      setUploading(false);\n')
f.write('      if (inputRef.current) inputRef.current.value = "";\n')
f.write('    }\n')
f.write('  };\n')
f.write('\n')
f.write('  const handleRemove = async () => {\n')
f.write('    await supabase.storage.from("scenario-media").remove([storagePath]);\n')
f.write('    onRemoved();\n')
f.write('  };\n')
f.write('\n')
f.write('  return (\n')
f.write('    <div className="flex items-center gap-2">\n')
f.write('      <input ref={inputRef} type="file" accept={accept} onChange={handleUpload} className="hidden" />\n')
f.write('      {currentUrl ? (\n')
f.write('        <div className="flex items-center gap-2 flex-1">\n')
f.write('          <Icon className="w-4 h-4 text-portal shrink-0" />\n')
f.write('          {type === "audio" ? (\n')
f.write('            <audio controls src={publicUrl} className="h-8 flex-1" />\n')
f.write('          ) : (\n')
f.write('            <img src={publicUrl} alt="" className="h-8 w-14 object-cover rounded border border-border" />\n')
f.write('          )}\n')
f.write('          <button onClick={handleRemove} className="text-muted-foreground hover:text-destructive transition-colors">\n')
f.write('            <X className="w-4 h-4" />\n')
f.write('          </button>\n')
f.write('        </div>\n')
f.write('      ) : (\n')
f.write('        <button onClick={() => inputRef.current?.click()} disabled={uploading}\n')
f.write('          className="flex items-center gap-2 text-xs text-muted-foreground hover:text-portal border border-dashed border-border hover:border-portal px-3 py-1.5 rounded-lg transition-all disabled:opacity-50">\n')
f.write('          {uploading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Upload className="w-3 h-3" />}\n')
f.write('          {type === "audio" ? "Аудио" : "Фото"}\n')
f.write('        </button>\n')
f.write('      )}\n')
f.write('      {error && <span className="text-xs text-destructive">{error}</span>}\n')
f.write('    </div>\n')
f.write('  );\n')
f.write('}\n')
f.close()
print('done')
