f = open('src/components/MediaPlayer.tsx', 'w', encoding='utf-8', newline='\n')
f.write('import { useEffect, useRef, useState } from "react";\n')
f.write('\n')
f.write('const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;\n')
f.write('\n')
f.write('function getPublicUrl(path: string) {\n')
f.write('  if (!path) return "";\n')
f.write('  return `${SUPABASE_URL}/storage/v1/object/public/scenario-media/${path}`;\n')
f.write('}\n')
f.write('\n')
f.write('interface MediaPlayerProps {\n')
f.write('  musicPath?: string;\n')
f.write('  volume?: number;\n')
f.write('}\n')
f.write('\n')
f.write('export function MediaPlayer({ musicPath, volume = 0.4 }: MediaPlayerProps) {\n')
f.write('  const audioRef = useRef<HTMLAudioElement | null>(null);\n')
f.write('  const [currentPath, setCurrentPath] = useState<string | undefined>(undefined);\n')
f.write('\n')
f.write('  useEffect(() => {\n')
f.write('    if (!musicPath || musicPath === currentPath) return;\n')
f.write('    setCurrentPath(musicPath);\n')
f.write('\n')
f.write('    const url = getPublicUrl(musicPath);\n')
f.write('    if (!url) return;\n')
f.write('\n')
f.write('    if (audioRef.current) {\n')
f.write('      // crossfade\n')
f.write('      const old = audioRef.current;\n')
f.write('      const fadeOut = setInterval(() => {\n')
f.write('        if (old.volume > 0.05) old.volume = Math.max(0, old.volume - 0.05);\n')
f.write('        else { clearInterval(fadeOut); old.pause(); old.src = ""; }\n')
f.write('      }, 100);\n')
f.write('    }\n')
f.write('\n')
f.write('    const audio = new Audio(url);\n')
f.write('    audio.loop = true;\n')
f.write('    audio.volume = 0;\n')
f.write('    audio.play().catch(() => {});\n')
f.write('    audioRef.current = audio;\n')
f.write('\n')
f.write('    // fade in\n')
f.write('    const fadeIn = setInterval(() => {\n')
f.write('      if (audio.volume < volume - 0.05) audio.volume = Math.min(volume, audio.volume + 0.05);\n')
f.write('      else { audio.volume = volume; clearInterval(fadeIn); }\n')
f.write('    }, 100);\n')
f.write('\n')
f.write('    return () => { clearInterval(fadeIn); };\n')
f.write('  }, [musicPath]);\n')
f.write('\n')
f.write('  useEffect(() => {\n')
f.write('    return () => { audioRef.current?.pause(); audioRef.current = null; };\n')
f.write('  }, []);\n')
f.write('\n')
f.write('  return null;\n')
f.write('}\n')
f.close()
print('done')
