f = open('src/components/BackgroundImage.tsx', 'w', encoding='utf-8', newline='\n')
f.write('import { useState, useEffect } from "react";\n')
f.write('\n')
f.write('const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;\n')
f.write('\n')
f.write('function getPublicUrl(path?: string) {\n')
f.write('  if (!path) return "";\n')
f.write('  return `${SUPABASE_URL}/storage/v1/object/public/scenario-media/${path}`;\n')
f.write('}\n')
f.write('\n')
f.write('interface BackgroundImageProps {\n')
f.write('  imagePath?: string;\n')
f.write('  overlay?: boolean;\n')
f.write('}\n')
f.write('\n')
f.write('export function BackgroundImage({ imagePath, overlay = true }: BackgroundImageProps) {\n')
f.write('  const [current, setCurrent] = useState("");\n')
f.write('  const [next, setNext] = useState("");\n')
f.write('  const [fading, setFading] = useState(false);\n')
f.write('\n')
f.write('  useEffect(() => {\n')
f.write('    const url = getPublicUrl(imagePath);\n')
f.write('    if (url === current) return;\n')
f.write('    if (!current) { setCurrent(url); return; }\n')
f.write('    setNext(url);\n')
f.write('    setFading(true);\n')
f.write('    const t = setTimeout(() => {\n')
f.write('      setCurrent(url);\n')
f.write('      setNext("");\n')
f.write('      setFading(false);\n')
f.write('    }, 800);\n')
f.write('    return () => clearTimeout(t);\n')
f.write('  }, [imagePath]);\n')
f.write('\n')
f.write('  if (!current && !next) return null;\n')
f.write('\n')
f.write('  return (\n')
f.write('    <div className="fixed inset-0 -z-10 overflow-hidden">\n')
f.write('      {current && (\n')
f.write('        <div className={`absolute inset-0 bg-cover bg-center transition-opacity duration-800 ${fading ? "opacity-0" : "opacity-100"}`}\n')
f.write('          style={{ backgroundImage: `url(${current})` }} />\n')
f.write('      )}\n')
f.write('      {next && (\n')
f.write('        <div className="absolute inset-0 bg-cover bg-center opacity-100"\n')
f.write('          style={{ backgroundImage: `url(${next})` }} />\n')
f.write('      )}\n')
f.write('      {overlay && <div className="absolute inset-0 bg-background/70" />}\n')
f.write('    </div>\n')
f.write('  );\n')
f.write('}\n')
f.close()
print('done')
