f = open('src/components/ReplicaPlayer.tsx', 'w', encoding='utf-8', newline='\n')
f.write('import { useEffect, useRef, useState } from "react";\n')
f.write('\n')
f.write('const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;\n')
f.write('\n')
f.write('function getPublicUrl(path?: string) {\n')
f.write('  if (!path) return "";\n')
f.write('  return `${SUPABASE_URL}/storage/v1/object/public/scenario-media/${path}`;\n')
f.write('}\n')
f.write('\n')
f.write('interface ReplicaPlayerProps {\n')
f.write('  speaker: "host" | "morty";\n')
f.write('  text: string;\n')
f.write('  audioPath?: string;\n')
f.write('  onFinished?: () => void;\n')
f.write('}\n')
f.write('\n')
f.write('const AVATARS = {\n')
f.write('  host: "https://api.dicebear.com/7.x/avataaars/svg?seed=rick&backgroundColor=b6e3f4",\n')
f.write('  morty: "https://api.dicebear.com/7.x/avataaars/svg?seed=morty&backgroundColor=ffd5dc",\n')
f.write('};\n')
f.write('\n')
f.write('const NAMES = { host: "Рик", morty: "Морти" };\n')
f.write('\n')
f.write('export function ReplicaPlayer({ speaker, text, audioPath, onFinished }: ReplicaPlayerProps) {\n')
f.write('  const audioRef = useRef<HTMLAudioElement | null>(null);\n')
f.write('  const [visible, setVisible] = useState(false);\n')
f.write('\n')
f.write('  useEffect(() => {\n')
f.write('    setVisible(true);\n')
f.write('    const url = getPublicUrl(audioPath);\n')
f.write('\n')
f.write('    if (url) {\n')
f.write('      const audio = new Audio(url);\n')
f.write('      audioRef.current = audio;\n')
f.write('      audio.play().catch(() => {});\n')
f.write('      audio.onended = () => { setVisible(false); setTimeout(() => onFinished?.(), 400); };\n')
f.write('    } else {\n')
f.write('      const timeout = setTimeout(() => {\n')
f.write('        setVisible(false);\n')
f.write('        setTimeout(() => onFinished?.(), 400);\n')
f.write('      }, Math.max(2000, text.length * 60));\n')
f.write('      return () => clearTimeout(timeout);\n')
f.write('    }\n')
f.write('\n')
f.write('    return () => { audioRef.current?.pause(); audioRef.current = null; };\n')
f.write('  }, [audioPath, text]);\n')
f.write('\n')
f.write('  return (\n')
f.write('    <div className={`fixed bottom-6 left-1/2 -translate-x-1/2 z-50 transition-all duration-400 ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}\n')
f.write('      style={{ maxWidth: "90vw", width: 480 }}>\n')
f.write('      <div className="glass-card p-4 flex items-start gap-3 border border-portal/30 shadow-lg">\n')
f.write('        <img src={AVATARS[speaker]} alt={NAMES[speaker]}\n')
f.write('          className="w-12 h-12 rounded-full border-2 border-portal/40 shrink-0" />\n')
f.write('        <div>\n')
f.write('          <p className="text-xs uppercase tracking-widest text-portal mb-1">{NAMES[speaker]}</p>\n')
f.write('          <p className="text-sm text-foreground leading-relaxed">{text}</p>\n')
f.write('        </div>\n')
f.write('      </div>\n')
f.write('    </div>\n')
f.write('  );\n')
f.write('}\n')
f.close()
print('done')
